CREATE TABLE IF NOT EXISTS articles (
articleid INTEGER NOT NULL PRIMARY KEY,
name TEXT NOT NULL,
category TEXT NOT NULL,
details TEXT NOT NULL,
coverurl TEXT NOT NULL);

INSERT INTO articles (articleid,name,category,details,coverurl)
VALUES(1, 'Blondine', 'French', 'There was once a king called Benin. He was good and all the world loved him; he was just and the wicked feared him. His wife, the Queen Doucette, was also good, and much beloved.\r\n\r\nThis happy pair had a daughter called the Princess Blondine, because of her superb fair hair, and she was as amiable and charming as her father the king and her mother the queen.', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/blondine.jpg'),
(58, 'Lament', 'French', 'One day it was announced to the king, that all his subjects demanded that he should marry again in order to have a son who should reign after him. He refused at first but finally yielded to the pressing desires of his people and said to his minister Leger:â€”\r\n\r\n"My dear friend, my subjects wish me to marry again but my heart is so sad because of the death of my cherished queen Doucette that I cannot undertake the task of seeking another wife. Go, then, my good Leger and find me a princess who will make my sweet Blondine happy. Go; I ask for nothing more. When you have found a perfect woman, you will demand her hand in marriage and conduct her to my court."\r\n\r\nLeger set off immediately, visited many courts and saw innumerable princessesâ€”ugly, humpbacked and wicked.', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/lament.jpg'),
(62, 'The Lost Queen', 'Scottish', 'At last he arrived at the kingdom of the monarch Turbulent, who had a lovely daughter, bright, winning and apparently good. Leger found her so charming, that he asked her hand in marriage for his king Benin, without sufficiently inquiring into her real character.', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/the-lost-queen.jpg'),
(64, 'Woman Of The Dunes', 'Scottish', 'Benin immediately resolved that Blondine should be wholly separated from the new queen and remain as before under the exclusive protection of the nurse who had taken care of her and who loved her tenderly.\r\n\r\nThe queen thus saw Blondine rarely, and when she met her by chance she could not wholly dissimulate the hatred she felt for her.', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/women-of-the-dunes.jpg'),
(66, 'The Highland Witch', 'Scottish', 'The ambitious queen Fourbette saw all this clearly and hated intensely the innocent and gentle Blondine. If she had not feared the rage of the king she would have made Blondine the most wretched child in the world.\r\n\r\nBenin had commanded that Blondine should never be left alone with the queen.', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/the-highland-witch.jpg'),
(68, 'The Secret Library', 'English', 'As she advanced, the forest became lighter, the grass was finer and the flowers more abundant. She saw many pretty birds singing melodiously and graceful squirrels, bounding along the branches of the trees.\r\n\r\nBlondine, who had no doubt that she was about to leave the forest and see her dear father again', 'http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/the-secret-library.jpg');